version: '3'

services:
  db:
    restart: always
    container_name: contracts_db
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=contracts
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234567890
  app:
    restart: always
    container_name: contracts_app
    image: app
    build:
      context: ./app
    volumes:
      - "./app:/app"
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=contracts
      - DB_USER=postgres
      - DB_PASSWORD=1234567890
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db