# Generated by Django 4.2.1 on 2023-05-29 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_alter_employee_options_alter_invoicematerial_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estimate',
            options={'verbose_name': 'Накладная', 'verbose_name_plural': 'Накладные'},
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='tech_lid',
        ),
        migrations.RemoveField(
            model_name='estimatematerial',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='estimate',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='contracts.supplier', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='contracts.employee', verbose_name='Специалист по закупкам'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='created_at',
            field=models.DateTimeField(verbose_name='Дата и Время поставки'),
        ),
    ]
