# Generated by Django 4.2.1 on 2023-05-29 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_rename_user_estimate_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='contracts.employee', verbose_name='Специалист по закупкам'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='contracts.supplier', verbose_name='Поставщик'),
        ),
    ]
