# Generated by Django 4.2.1 on 2023-05-30 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_alter_estimate_description_alter_estimate_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_of_hiring',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата найма'),
        ),
    ]
